[package]
name = "merk"
description = "Merkle key/value store"
version = "1.0.0"
authors = ["Matt Bell <mappum@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
tempdir = "0.3.7"
storage = { path = "../storage" }
thiserror = "1.0.30"
rocksdb = { git = "https://github.com/yiyuanliu/rust-rocksdb", branch = "transaction" }
anyhow = "1.0.51"
failure = "0.1.8"

[dependencies.time]
version = "0.3.6"
optional = true

[dependencies.hex]
version = "0.4.2"
optional = true

[dependencies.colored]
version = "1.8.0"
optional = true

[dependencies.num_cpus]
version = "1.10.0"
optional = true

[dependencies.byteorder]
version = "1.3.2" 
optional = true

[dependencies.ed]
version = "0.1.6"
optional = true

[dependencies.blake3]
version = "0.3.7"
optional = true

[dependencies.rand]
version = "0.8.3"
features = ["small_rng"]
optional = true

[dependencies.jemallocator]
version = "0.3.2"
features = ["disable_initial_exec_tls"]
optional = true

[features]
default = ["full", "verify"]
full = ["rand", 
        "time",
        "hex", 
        "colored",
        "num_cpus",
        "byteorder",
        "ed",
        "blake3",
        "jemallocator"
]
verify = ["ed",
          "blake3"
]
