[package]
name = "grovedb"
version = "0.3.1"
edition = "2021"

[dependencies]
rs_merkle = "1.1.0"
merk = { path = "../merk", features = ["full"] }
thiserror = "1.0.30"
tempfile = "3"
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
storage = { path = "../storage", features = ["rocksdb_storage"] }
visualize = { path = "../visualize" }
hex = "0.4.3"
itertools = { version = "0.10.3", optional = true }
integer-encoding = "3.0.3"
intrusive-collections = "0.9.3"
costs = { version = "0.0.0", path = "../costs" }

[dev-dependencies]
rand = "0.8.4"
criterion = "0.3"
hex = "0.4.3"

[[bench]]
name = "insertion_benchmark"
harness = false
