[package]
name = "grovedb"
version = "0.3.1"
edition = "2021"

[dependencies]
rs_merkle = "1.1.0"
merk = { path = "../merk", features = ["full"] }
thiserror = "1.0.30"
tempdir = "0.3.7"
bincode = "1.3.3"
serde = { version = "1.0.136", features = ["derive"] }
storage = { path = "../storage", features = ["rocksdb_storage"] }
hex = "0.4.3"
itertools = { version = "0.10.3", optional = true }

[dev-dependencies]
rand = "0.8.4"

[features]
default = ["visualize"]
visualize = ["itertools"]

[lib]
doctest = false
