[package]
name = "grovedb"
version = "0.3.1"
edition = "2021"

[dependencies]
rs_merkle = "1.1.0"
merk = { path = "../merk", features = ["full"] }
thiserror = "1.0.30"
tempdir = "0.3.7"
bincode = "1.3.3"
serde = { version = "1.0.130", features = ["derive"] }
storage = { path = "../storage" }
hex = "0.4.3"
blake3 = "1.3.0"

[dev-dependencies]
rand = "0.8.4"

[features]
default = ["visualize"]
visualize = []
