[package]
name = "storage"
version = "0.2.0"
edition = "2021"

[dependencies]
lazy_static = { version = "1.4.0", optional = true }
num_cpus = { version = "1.13.1", optional = true }
tempfile = { version = "3.3.0", optional = true }
blake3 = { version = "1.3.1", optional = true }
indexmap = { version = "1.8.2", optional = true }
visualize = { path = "../visualize" }
strum = { version = "0.24.0", features = ["derive"] }


[dependencies.rocksdb]
git = "https://github.com/quantumexplorer/rust-rocksdb"
branch = "fix/optimisticDBWriteBatch"
optional = true

[features]
rocksdb_storage = ["rocksdb", "num_cpus", "lazy_static", "tempfile", "blake3", "indexmap"]
