on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

name: Node.JS binding tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Install NPM deps
        run: npm ci

      - name: Build Node.JS binding
        run: npm run build

      - name: Run tests
        run: npm test

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Install NPM deps
        run: npm ci

      - name: Run ES linter
        run: npm run lint