name: Release

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

#  release:
#    types:
#      - published

jobs:
  build:
    name: Build Node.JS binding

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            compiler: gnu
            platform: unknown-linux
#          - os: ubuntu-latest
#            arch: aarch64
#            node_arch: arm64
#            compiler: gnu
#            platform: unknown-linux
#            build_dependencies:
#              - gcc-aarch64-linux-gnu
#              - binutils-aarch64-linux-gnu
#              - clang
          - os: ubuntu-latest
            arch: x86_64
            compiler: musl
            platform: unknown-linux
            build_dependencies:
              - musl-tools
#          - os: ubuntu-latest
#            arch: aarch64
#            node_arch: arm64
#            compiler: musl
#            platform: unknown-linux
#            build_dependencies:
#              - gcc-aarch64-linux-gnu
#              - binutils-aarch64-linux-gnu
#              - clang
#              - musl-tools
#              - musl
##              - musl:arm64
          - os: macos-11
            arch: x86_64
            platform: apple-darwin
          - os: macos-11
            arch: aarch64
            node_arch: arm64
            platform: apple-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install NPM deps
        run: npm ci

      - name: Set target name
        uses: actions/github-script@v5
        id: set-target
        with:
          script: |
            let target = '${{ matrix.arch }}-${{ matrix.platform }}';
            
            if ('${{ matrix.compiler }}') {
              target += '-${{ matrix.compiler }}';
            }
            
            core.info(`Set target ${target}`);
            
            return target;
          result-encoding: string

#      - name: Add arm64 architecture for apt
#        if: ${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64' }}
#        run: sudo dpkg --add-architecture arm64

      - name: Install build deps
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.build_dependencies && matrix.build_dependencies[0] }}
        run: |
          sudo apt-get update
          sudo apt-get install ${{ join(matrix.build_dependencies, ' ') }}

      - name: Fix missing "musl-g++" for x86_64-unknown-linux-musl # https://github.com/rust-lang/cargo/issues/3359
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'x86_64' && matrix.compiler == 'musl' }}
        run: sudo ln -s /bin/g++ /bin/musl-g++

      - name: Setup Rust toolchain and target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          target: ${{ steps.set-target.outputs.result }}

      - name: Set defualt target
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: .cargo/config.toml
          write-mode: append
          contents: |
            
            [build]
            target = "${{ steps.set-target.outputs.result }}"

      - name: Set LIBC env
        uses: actions/github-script@v5
        id: set-libc
        with:
          script: |
            let env = '';

            if (${{ matrix.compiler == 'musl' }}) {
              env = 'musl'
            }

            core.info(`Set LIBC env to "${env}"`);

            return env;
          result-encoding: string

#      - name: Run tests
#        run: npm test
#        env:
#            LIBC: ${{ matrix.compiler == 'musl' }}
#            ARCH: ${{ matrix.node_arch }} # Overwrite current arch with target one

      - name: Build
        run: npm run build:release
        env:
          LIBC: ${{ steps.set-libc.outputs.result }}
          ARCH: ${{ matrix.node_arch }} # Overwrite current arch with target one

      - name: Upload prebuild artifacts
        uses: actions/upload-artifact@v2
        with:
          name: prebuilds
          path: node-grove/prebuilds/

  publish:
    name: Publish NPM Package
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
#
#      - name: Check package version matches tag
#        uses: geritol/match-tag-to-package-version@0.2.0
#        env:
#          TAG_PREFIX: v
#
      - name: Setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM deps
        run: npm ci

      - name: Download prebuild artifacts
        uses: actions/download-artifact@v2
        with:
          name: prebuilds
          path: node-grove/prebuilds

      - name: Check prebuilds
        run: ls -laR node-grove/prebuilds

#      - name: NPM Publish
#        run: npm publish --access public
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
